# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filter/filter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'filter/filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ilter/filter.proto\x12\x0cproto.filter\"M\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06module\x18\x04 \x01(\t\"=\n\x0e\x46ilterCriteria\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05\x65xact\x18\x03 \x01(\x08\"\xe4\x01\n\x0eSegmentRequest\x12\x12\n\nsegment_id\x18\x01 \x01(\x05\x12\x14\n\x0csegment_type\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\t\x12$\n\x04logs\x18\x05 \x03(\x0b\x32\x16.proto.filter.LogEntry\x12-\n\x0bplugin_type\x18\x06 \x01(\x0e\x32\x18.proto.filter.PluginType\x12-\n\x07\x66ilters\x18\x07 \x03(\x0b\x32\x1c.proto.filter.FilterCriteria\"\xc9\x01\n\x0fSegmentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12$\n\x04logs\x18\x03 \x03(\x0b\x32\x16.proto.filter.LogEntry\x12=\n\x08metadata\x18\x04 \x03(\x0b\x32+.proto.filter.SegmentResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*%\n\nPluginType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x46ILTER\x10\x01\x32^\n\rPluginService\x12M\n\x0eProcessSegment\x12\x1c.proto.filter.SegmentRequest\x1a\x1d.proto.filter.SegmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filter.filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PLUGINTYPE']._serialized_start=614
  _globals['_PLUGINTYPE']._serialized_end=651
  _globals['_LOGENTRY']._serialized_start=37
  _globals['_LOGENTRY']._serialized_end=114
  _globals['_FILTERCRITERIA']._serialized_start=116
  _globals['_FILTERCRITERIA']._serialized_end=177
  _globals['_SEGMENTREQUEST']._serialized_start=180
  _globals['_SEGMENTREQUEST']._serialized_end=408
  _globals['_SEGMENTRESPONSE']._serialized_start=411
  _globals['_SEGMENTRESPONSE']._serialized_end=612
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_start=565
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_end=612
  _globals['_PLUGINSERVICE']._serialized_start=653
  _globals['_PLUGINSERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
